### ISSUE TITLE
Variables "z" and "zm" are geopotential height (at mid-levels), not geopotential

### ISSUE THREAD

**Issue by nusbaume** [NCAR/atmospheric_physics#11]
In the `Kessler.meta` and `geopotential_t.meta` files, the variables `z` and `zm` should be the geopotential height at mid-levels.  However, their standard names have them labeled "geopotential", which is a different physical quantity.  

These standard names should thus be modified to state "geopotential height", not just "geopotential".  Otherwise there is a high risk that a future user or developer will use these variables in an incorrect way.

**Comment by gold2718** [comment]
The standard name library has been moved and the new repo is [here](https://github.com/ESCOMP/CCPPStandardNames). 
For now, the standard name page is [just a file in that repo](https://github.com/ESCOMP/CCPPStandardNames/blob/master/Metadata-standard-names.md).

**Comment by gold2718** [comment]
One issue is whether the name `geopotential` itself is ever really correct in current usage. While I took this name from GFS physics (e.g., the standard name library currently has `geopotential_at_surface`), it is really `geopotential_per_unit_mass`. Is it worth trying to get that change accepted?

**Comment by nusbaume** [comment]
In an ideal world, yes, I think it would be good to have the names be as exact as possible.  

However, if that is difficult to change then I personally believe it is ok to not include the "per_unit_mass" text.  The reason being that if most of our users have an atmospheric science background, then the fluid dynamics equations they were exposed to were likely derived in a "per unit mass" framework, so the user would likely implicitly assume that the variables are all per unit mass, at least in most situations.

**Comment by gold2718** [comment]
This was fixed in #8.
