### ISSUE TITLE
Issues with ordering of loops for Kessler

### ISSUE THREAD

**Issue by cacraigucar** [NCAR/atmospheric_physics#9]
A brief conversation with Brian Eaton indicated that there are issues with the ordering of some of the loops in kessler.  More details will be added once we have had an in-person discussion.

**Comment by brian-eaton** [comment]
I looked at this further and realized that I was mistaken about this.  I hadn't realized that the CAM interface was switching the vertical order of the input arrays, and just assumed the kessler algorithm was using the standard CAM top to bottom order.  I will recheck the details in the kessler.F90 file.

**Comment by brian-eaton** [comment]
I've looked at the loops again now that I know which way is up:)  They look OK.  In my opinion, the loops are now harder to read than the originals due to using long names for indices.

**Comment by gold2718** [comment]
I think this was fixed in #5. @cacraigucar, if you agree, please close this issue. Otherwise, Please add more information about what needs to be done.
